# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iteasyinstall.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iteasyinstall.proto',
  package='iteasyinstall',
  serialized_pb='\n\x13iteasyinstall.proto\x12\riteasyinstall\">\n\x14PkgCheckUserPassword\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x14\n\x0cuserpassword\x18\x02 \x02(\t\";\n\x19PkgCheckUserPasswordReply\x12\x11\n\tissuccess\x18\x01 \x02(\x08\x12\x0b\n\x03\x65rr\x18\x02 \x02(\t\"W\n\x11PkgModifyPassword\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x17\n\x0fuseroldpassword\x18\x02 \x02(\t\x12\x17\n\x0fusernewpassword\x18\x03 \x02(\t\"8\n\x16PkgModifyPasswordReply\x12\x11\n\tissuccess\x18\x01 \x02(\x08\x12\x0b\n\x03\x65rr\x18\x02 \x02(\t\"8\n\x0ePkgQueryConfig\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x14\n\x0cuserpassword\x18\x02 \x02(\t\"\xce\x01\n\x13PkgQueryConfigReply\x12\x11\n\tissuccess\x18\x01 \x02(\x08\x12\x0b\n\x03\x65rr\x18\x02 \x02(\t\x12\x11\n\tcompanyid\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65partmentid\x18\x04 \x01(\t\x12\x0e\n\x06userid\x18\x05 \x01(\t\x12\x10\n\x08serverid\x18\x06 \x01(\t\x12\x10\n\x08serverip\x18\x07 \x01(\t\x12\x12\n\nserverport\x18\x08 \x01(\x05\x12\x12\n\nserverdesc\x18\t \x01(\t\x12\x12\n\nsuploadurl\x18\n \x01(\t\"\xd6\x01\n\x12PkgMongoDBUserInfo\x12\x0e\n\x06userid\x18\x01 \x02(\t\x12\x10\n\x08username\x18\x02 \x02(\t\x12\x10\n\x08userpass\x18\x03 \x02(\t\x12\x12\n\ndepartment\x18\x04 \x01(\t\x12\x10\n\x08truename\x18\x05 \x01(\t\x12\x0f\n\x07isadmin\x18\x06 \x01(\x08\x12\x12\n\ncanencrypt\x18\x07 \x01(\x08\x12\x13\n\x0bofflinetime\x18\x08 \x01(\x05\x12\x17\n\x0freqpinginterval\x18\t \x01(\x05\x12\x13\n\x0b\x63ompanyname\x18\n \x01(\t')




_PKGCHECKUSERPASSWORD = _descriptor.Descriptor(
  name='PkgCheckUserPassword',
  full_name='iteasyinstall.PkgCheckUserPassword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='iteasyinstall.PkgCheckUserPassword.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userpassword', full_name='iteasyinstall.PkgCheckUserPassword.userpassword', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=100,
)


_PKGCHECKUSERPASSWORDREPLY = _descriptor.Descriptor(
  name='PkgCheckUserPasswordReply',
  full_name='iteasyinstall.PkgCheckUserPasswordReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='issuccess', full_name='iteasyinstall.PkgCheckUserPasswordReply.issuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err', full_name='iteasyinstall.PkgCheckUserPasswordReply.err', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=161,
)


_PKGMODIFYPASSWORD = _descriptor.Descriptor(
  name='PkgModifyPassword',
  full_name='iteasyinstall.PkgModifyPassword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='iteasyinstall.PkgModifyPassword.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='useroldpassword', full_name='iteasyinstall.PkgModifyPassword.useroldpassword', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usernewpassword', full_name='iteasyinstall.PkgModifyPassword.usernewpassword', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=163,
  serialized_end=250,
)


_PKGMODIFYPASSWORDREPLY = _descriptor.Descriptor(
  name='PkgModifyPasswordReply',
  full_name='iteasyinstall.PkgModifyPasswordReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='issuccess', full_name='iteasyinstall.PkgModifyPasswordReply.issuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err', full_name='iteasyinstall.PkgModifyPasswordReply.err', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=252,
  serialized_end=308,
)


_PKGQUERYCONFIG = _descriptor.Descriptor(
  name='PkgQueryConfig',
  full_name='iteasyinstall.PkgQueryConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='iteasyinstall.PkgQueryConfig.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userpassword', full_name='iteasyinstall.PkgQueryConfig.userpassword', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=310,
  serialized_end=366,
)


_PKGQUERYCONFIGREPLY = _descriptor.Descriptor(
  name='PkgQueryConfigReply',
  full_name='iteasyinstall.PkgQueryConfigReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='issuccess', full_name='iteasyinstall.PkgQueryConfigReply.issuccess', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err', full_name='iteasyinstall.PkgQueryConfigReply.err', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='companyid', full_name='iteasyinstall.PkgQueryConfigReply.companyid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='departmentid', full_name='iteasyinstall.PkgQueryConfigReply.departmentid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userid', full_name='iteasyinstall.PkgQueryConfigReply.userid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverid', full_name='iteasyinstall.PkgQueryConfigReply.serverid', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverip', full_name='iteasyinstall.PkgQueryConfigReply.serverip', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverport', full_name='iteasyinstall.PkgQueryConfigReply.serverport', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverdesc', full_name='iteasyinstall.PkgQueryConfigReply.serverdesc', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='suploadurl', full_name='iteasyinstall.PkgQueryConfigReply.suploadurl', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=369,
  serialized_end=575,
)


_PKGMONGODBUSERINFO = _descriptor.Descriptor(
  name='PkgMongoDBUserInfo',
  full_name='iteasyinstall.PkgMongoDBUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='iteasyinstall.PkgMongoDBUserInfo.userid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='iteasyinstall.PkgMongoDBUserInfo.username', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userpass', full_name='iteasyinstall.PkgMongoDBUserInfo.userpass', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='department', full_name='iteasyinstall.PkgMongoDBUserInfo.department', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='truename', full_name='iteasyinstall.PkgMongoDBUserInfo.truename', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isadmin', full_name='iteasyinstall.PkgMongoDBUserInfo.isadmin', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canencrypt', full_name='iteasyinstall.PkgMongoDBUserInfo.canencrypt', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offlinetime', full_name='iteasyinstall.PkgMongoDBUserInfo.offlinetime', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reqpinginterval', full_name='iteasyinstall.PkgMongoDBUserInfo.reqpinginterval', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='companyname', full_name='iteasyinstall.PkgMongoDBUserInfo.companyname', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=578,
  serialized_end=792,
)

DESCRIPTOR.message_types_by_name['PkgCheckUserPassword'] = _PKGCHECKUSERPASSWORD
DESCRIPTOR.message_types_by_name['PkgCheckUserPasswordReply'] = _PKGCHECKUSERPASSWORDREPLY
DESCRIPTOR.message_types_by_name['PkgModifyPassword'] = _PKGMODIFYPASSWORD
DESCRIPTOR.message_types_by_name['PkgModifyPasswordReply'] = _PKGMODIFYPASSWORDREPLY
DESCRIPTOR.message_types_by_name['PkgQueryConfig'] = _PKGQUERYCONFIG
DESCRIPTOR.message_types_by_name['PkgQueryConfigReply'] = _PKGQUERYCONFIGREPLY
DESCRIPTOR.message_types_by_name['PkgMongoDBUserInfo'] = _PKGMONGODBUSERINFO

class PkgCheckUserPassword(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PKGCHECKUSERPASSWORD

  # @@protoc_insertion_point(class_scope:iteasyinstall.PkgCheckUserPassword)

class PkgCheckUserPasswordReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PKGCHECKUSERPASSWORDREPLY

  # @@protoc_insertion_point(class_scope:iteasyinstall.PkgCheckUserPasswordReply)

class PkgModifyPassword(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PKGMODIFYPASSWORD

  # @@protoc_insertion_point(class_scope:iteasyinstall.PkgModifyPassword)

class PkgModifyPasswordReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PKGMODIFYPASSWORDREPLY

  # @@protoc_insertion_point(class_scope:iteasyinstall.PkgModifyPasswordReply)

class PkgQueryConfig(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PKGQUERYCONFIG

  # @@protoc_insertion_point(class_scope:iteasyinstall.PkgQueryConfig)

class PkgQueryConfigReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PKGQUERYCONFIGREPLY

  # @@protoc_insertion_point(class_scope:iteasyinstall.PkgQueryConfigReply)

class PkgMongoDBUserInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PKGMONGODBUSERINFO

  # @@protoc_insertion_point(class_scope:iteasyinstall.PkgMongoDBUserInfo)


# @@protoc_insertion_point(module_scope)
