/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.6 at Sat Mar 15 15:19:57 2014. */

#ifndef _PB_FILEPROTO_PB_H_
#define _PB_FILEPROTO_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _FileInfo {
    uint64_t inode;
    pb_callback_t name;
} FileInfo;

typedef struct _ListFilesRequest {
    pb_callback_t path;
} ListFilesRequest;

typedef struct _ListFilesResponse {
    bool has_path_error;
    bool path_error;
    pb_callback_t file;
} ListFilesResponse;

/* Default values for struct fields */
extern const bool ListFilesResponse_path_error_default;

/* Field tags (for use in manual encoding/decoding) */
#define FileInfo_inode_tag                       1
#define FileInfo_name_tag                        2
#define ListFilesRequest_path_tag                1
#define ListFilesResponse_path_error_tag         1
#define ListFilesResponse_file_tag               2

/* Struct field encoding specification for nanopb */
extern const pb_field_t ListFilesRequest_fields[2];
extern const pb_field_t FileInfo_fields[3];
extern const pb_field_t ListFilesResponse_fields[3];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
