/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.6 at Sat Mar 15 15:19:57 2014. */

#include "fileproto.pb.h"

const bool ListFilesResponse_path_error_default = false;


const pb_field_t ListFilesRequest_fields[2] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, CALLBACK, FIRST, ListFilesRequest, path, path, 0),
    PB_LAST_FIELD
};

const pb_field_t FileInfo_fields[3] = {
    PB_FIELD2(  1, UINT64  , REQUIRED, STATIC  , FIRST, FileInfo, inode, inode, 0),
    PB_FIELD2(  2, STRING  , REQUIRED, CALLBACK, OTHER, FileInfo, name, inode, 0),
    PB_LAST_FIELD
};

const pb_field_t ListFilesResponse_fields[3] = {
    PB_FIELD2(  1, BOOL    , OPTIONAL, STATIC  , FIRST, ListFilesResponse, path_error, path_error, &ListFilesResponse_path_error_default),
    PB_FIELD2(  2, MESSAGE , REPEATED, CALLBACK, OTHER, ListFilesResponse, file, path_error, &FileInfo_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
STATIC_ASSERT((pb_membersize(ListFilesResponse, file) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ListFilesRequest_FileInfo_ListFilesResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
STATIC_ASSERT((pb_membersize(ListFilesResponse, file) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ListFilesRequest_FileInfo_ListFilesResponse)
#endif


