/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.6 at Sat Mar 15 09:59:35 2014. */

#include "iteasycomm.pb.h"



const pb_field_t iteasycomm_PkgPing_fields[2] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, iteasycomm_PkgPing, id, id, 0),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgLoginReq_fields[5] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, iteasycomm_PkgLoginReq, username, username, 0),
    PB_FIELD2(  2, STRING  , REQUIRED, CALLBACK, OTHER, iteasycomm_PkgLoginReq, password, username, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, CALLBACK, OTHER, iteasycomm_PkgLoginReq, policylastid, password, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, CALLBACK, OTHER, iteasycomm_PkgLoginReq, policyinlinelastid, policylastid, 0),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgLoginReply_fields[5] = {
    PB_FIELD2(  1, BOOL    , REQUIRED, STATIC  , FIRST, iteasycomm_PkgLoginReply, issuccess, issuccess, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, CALLBACK, OTHER, iteasycomm_PkgLoginReply, servertime, issuccess, 0),
    PB_FIELD2(  3, INT32   , OPTIONAL, STATIC  , OTHER, iteasycomm_PkgLoginReply, reqpinginterval, servertime, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, CALLBACK, OTHER, iteasycomm_PkgLoginReply, err, reqpinginterval, 0),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgLogReq_fields[2] = {
    PB_FIELD2(  1, MESSAGE , REPEATED, CALLBACK, FIRST, iteasycomm_PkgLogReq, logreqlist, logreqlist, &iteasycomm_PkgLogReq_StruLogReq_fields),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgLogReq_StruLogReq_fields[6] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, iteasycomm_PkgLogReq_StruLogReq, id, id, 0),
    PB_FIELD2(  2, STRING  , REQUIRED, CALLBACK, OTHER, iteasycomm_PkgLogReq_StruLogReq, logtime, id, 0),
    PB_FIELD2(  3, INT32   , REQUIRED, STATIC  , OTHER, iteasycomm_PkgLogReq_StruLogReq, logtype, logtime, 0),
    PB_FIELD2(  4, INT32   , REQUIRED, STATIC  , OTHER, iteasycomm_PkgLogReq_StruLogReq, loglevel, logtype, 0),
    PB_FIELD2(  5, STRING  , REQUIRED, CALLBACK, OTHER, iteasycomm_PkgLogReq_StruLogReq, logcontent, loglevel, 0),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgLogReply_fields[2] = {
    PB_FIELD2(  1, MESSAGE , REPEATED, CALLBACK, FIRST, iteasycomm_PkgLogReply, logreplylist, logreplylist, &iteasycomm_PkgLogReply_StruLogReply_fields),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgLogReply_StruLogReply_fields[3] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC  , FIRST, iteasycomm_PkgLogReply_StruLogReply, id, id, 0),
    PB_FIELD2(  2, BOOL    , REQUIRED, STATIC  , OTHER, iteasycomm_PkgLogReply_StruLogReply, issuccess, id, 0),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgPolicyPush_fields[6] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, iteasycomm_PkgPolicyPush, policylastid, policylastid, 0),
    PB_FIELD2(  2, STRING  , REQUIRED, CALLBACK, OTHER, iteasycomm_PkgPolicyPush, policyprocessname, policylastid, 0),
    PB_FIELD2(  3, STRING  , REQUIRED, CALLBACK, OTHER, iteasycomm_PkgPolicyPush, policyextfilename, policyprocessname, 0),
    PB_FIELD2(  4, STRING  , REQUIRED, CALLBACK, OTHER, iteasycomm_PkgPolicyPush, policydisableprocessname, policyextfilename, 0),
    PB_FIELD2(  5, INT32   , REQUIRED, STATIC  , OTHER, iteasycomm_PkgPolicyPush, policyofflinetime, policydisableprocessname, 0),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgPolicyEcho_fields[3] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, iteasycomm_PkgPolicyEcho, policylastid, policylastid, 0),
    PB_FIELD2(  2, BOOL    , REQUIRED, STATIC  , OTHER, iteasycomm_PkgPolicyEcho, issuccess, policylastid, 0),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgPolicyinlinePush_fields[3] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, iteasycomm_PkgPolicyinlinePush, policyinlinelastid, policyinlinelastid, 0),
    PB_FIELD2(  2, STRING  , REQUIRED, CALLBACK, OTHER, iteasycomm_PkgPolicyinlinePush, policyinlinefile, policyinlinelastid, 0),
    PB_LAST_FIELD
};

const pb_field_t iteasycomm_PkgPolicyinlineEcho_fields[3] = {
    PB_FIELD2(  1, STRING  , REQUIRED, CALLBACK, FIRST, iteasycomm_PkgPolicyinlineEcho, policylastid, policylastid, 0),
    PB_FIELD2(  2, BOOL    , REQUIRED, STATIC  , OTHER, iteasycomm_PkgPolicyinlineEcho, issuccess, policylastid, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
STATIC_ASSERT((pb_membersize(iteasycomm_PkgLogReq, logreqlist) < 65536 && pb_membersize(iteasycomm_PkgLogReply, logreplylist) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_iteasycomm_PkgPing_iteasycomm_PkgLoginReq_iteasycomm_PkgLoginReply_iteasycomm_PkgLogReq_iteasycomm_PkgLogReq_StruLogReq_iteasycomm_PkgLogReply_iteasycomm_PkgLogReply_StruLogReply_iteasycomm_PkgPolicyPush_iteasycomm_PkgPolicyEcho_iteasycomm_PkgPolicyinlinePush_iteasycomm_PkgPolicyinlineEcho)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
STATIC_ASSERT((pb_membersize(iteasycomm_PkgLogReq, logreqlist) < 256 && pb_membersize(iteasycomm_PkgLogReply, logreplylist) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_iteasycomm_PkgPing_iteasycomm_PkgLoginReq_iteasycomm_PkgLoginReply_iteasycomm_PkgLogReq_iteasycomm_PkgLogReq_StruLogReq_iteasycomm_PkgLogReply_iteasycomm_PkgLogReply_StruLogReply_iteasycomm_PkgPolicyPush_iteasycomm_PkgPolicyEcho_iteasycomm_PkgPolicyinlinePush_iteasycomm_PkgPolicyinlineEcho)
#endif


